config/routes.rb
Rails.application.routes.draw do
  root to: "collections#index"

  resources :collections, only: [:index]
end

app/models/collection.rb
class Collection < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/collections_controller.rb
class CollectionsController < ApplicationController
  def index
    @collections = Collection.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/collections/_collection.html.erb
<div class="third-width">
  <div class="collection-item">
    <div class="card-block">
      <h2 class="collection-title js-clamp-1">
        <a href="#">
          <%= collection.name %>
        </a>
      </h2>
      <div class="card-text collection-description-container">
        <p class="collection-description js-clamp-3"><%= collection.description %></p>
      </div>
      <a href="#" class="btn btn-sm btn-primary-outline">View 3 documents</a>
    </div>
  </div>
</div>

app/views/collections/index.html.erb
<div class="row">
  <div class="col-lg-12">
    <h1>Collections</h1>
  </div>
</div>

<section class="row">
  <%= render @collections %>
</section>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-light bg-faded">
  <div class="container">
    <%= link_to "Live Guides", root_path, class: "navbar-brand" %>
    <ul class="nav navbar-nav">
      <%= link_to "Collections", collections_path, class: "nav-item nav-link" %>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Liveguides</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'https://cdnjs.cloudflare.com/ajax/libs/Clamp.js/0.5.1/clamp.min.js' %>
  <%= csrf_meta_tags %>
</head>
<body>

  <%= render partial: "layouts/navbar" %>
  <main class="container"%>
    <%= yield %>
  </main>

</body>
</html>